version: "3.8"

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d chatbot" ]
      interval: 5s
      timeout: 3s
      retries: 5

  ollama:
    image: ollama/ollama
    volumes:
      - ~/.ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

  my-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://user:password@db:5432/chatbot
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    command: ["sh", "-c", "until pg_isready -h db -p 5432 -U user; do echo 'Waiting for DB...'; sleep 2; done; pnpm run migrate && pnpm start"]
    restart: always

volumes:
  db_data: